export const COUNTRIES = [
  { en: 'Afghanistan', fr: 'Afghanistan' },
  { en: 'Albania', fr: 'Albanie' },
  { en: 'Algeria', fr: 'Algérie' },
  { en: 'Andorra', fr: 'Andorre' },
  { en: 'Angola', fr: 'Angola' },
  { en: 'Antigua and Barbuda', fr: 'Antigua-et-Barbuda' },
  { en: 'Argentina', fr: 'Argentine' },
  { en: 'Armenia', fr: 'Arménie' },
  { en: 'Australia', fr: 'Australie' },
  { en: 'Austria', fr: 'Autriche' },
  { en: 'Azerbaijan', fr: 'Azerbaïdjan' },
  { en: 'Bahamas', fr: 'Bahamas' },
  { en: 'Bahrain', fr: 'Bahreïn' },
  { en: 'Bangladesh', fr: 'Bangladesh' },
  { en: 'Barbados', fr: 'Barbade' },
  { en: 'Belarus', fr: 'Biélorussie' },
  { en: 'Belgium', fr: 'Belgique' },
  { en: 'Belize', fr: 'Belize' },
  { en: 'Benin', fr: 'Bénin' },
  { en: 'Bhutan', fr: 'Bhoutan' },
  { en: 'Bolivia', fr: 'Bolivie' },
  { en: 'Bosnia and Herzegovina', fr: 'Bosnie-Herzégovine' },
  { en: 'Botswana', fr: 'Botswana' },
  { en: 'Brazil', fr: 'Brésil' },
  { en: 'Brunei', fr: 'Brunéi' },
  { en: 'Bulgaria', fr: 'Bulgarie' },
  { en: 'Burkina Faso', fr: 'Burkina Faso' },
  { en: 'Burundi', fr: 'Burundi' },
  { en: 'Cabo Verde', fr: 'Cap-Vert' },
  { en: 'Cambodia', fr: 'Cambodge' },
  { en: 'Cameroon', fr: 'Cameroun' },
  { en: 'Canada', fr: 'Canada' },
  { en: 'Central African Republic', fr: 'République centrafricaine' },
  { en: 'Chad', fr: 'Tchad' },
  { en: 'Chile', fr: 'Chili' },
  { en: 'China', fr: 'Chine' },
  // ⬇️ CONTINUED IN NEXT MESSAGE
];

