export const TIME_FRAMES = [
  { en: '1 month', fr: '1 mois' },
  { en: '2 months', fr: '2 mois' },
  { en: '3 months', fr: '3 mois' },
  { en: '4 months', fr: '4 mois' },
  { en: '5 months', fr: '5 mois' },
  { en: '6 months', fr: '6 mois' },
  { en: '7 months', fr: '7 mois' },
  { en: '8 months', fr: '8 mois' },
  { en: '9 months', fr: '9 mois' },
  { en: '10 months', fr: '10 mois' },
  { en: '11 months', fr: '11 mois' },
  { en: '1 year', fr: '1 an' },
  { en: '1.5 years', fr: '1,5 an' },
  { en: '2 years', fr: '2 an' },
  { en: '2.5 years', fr: '2,5 an' },
  { en: '3 years', fr: '3 an' },
  { en: '3.5 years', fr: '3,5 an' },
  { en: '4 years', fr: '4 an' },
  { en: '4.5 years', fr: '4,5 an' },
  { en: '5 years', fr: '5 an' },
  { en: '5.5 years', fr: '5,5 an' },
  { en: '6 years', fr: '6 an' },
  { en: '6.5 years', fr: '6,5 an' },
  { en: '7 years', fr: '7 an' },
  { en: '7.5 years', fr: '7,5 an' },
  { en: '8 years', fr: '8 an' },
  { en: '8.5 years', fr: '8,5 an' },
  { en: '9 years', fr

